on: push
name: Run tests
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Message that will be displayed on users'' first issue'
          pr-message: 'Message that will be displayed on users'' first pr'
      - run: echo All Done!
