on: push
name: Run tests
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: actions/hello-world@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_VAR1: a_variable
        with:
          first_name: Mona
          middle_name: The
          last_name: Octocat
      - run: echo All Done!
